version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insightful
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/backend
    env_file:
      - ./apps/backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./apps/backend:/app
    command: yarn start:dev

volumes:
  db_data:
